version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file samTemplate.yml --s3-bucket bk-lambda-pipeline --output-template-file outputSamTemplate.yml
artifacts:
  files:
    - outputSamTemplate.yml    