version: 0.2
phases:
  build:
    commands:
      # Package SAM template
      - sam package --template-file samTemplate.yml --s3-bucket bk-lambda-pipeline --output-template-file outputSamTemplate.yaml
      # Deploy packaged SAM template
      - sam deploy --template-file outputSamTemplate.yaml --stack-name ShowStack --capabilities CAPABILITY_IAM --parameter-overrides EnvironmentName=prod
