version: 0.2
phases:
  build:
    commands:
      - sam build
      - sam deploy --template-file samTemplate.yaml --stack-name DevStack --capabilities CAPABILITY_IAM --parameter-overrides EnvironmentName=Dev
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml