version: 0.2
phases:
  install:
  build:
    commands:
      - sam package --template-file samTemplate.yml --s3-bucket newpackages --output-template-file outputSamTemplate.yml
      - sam deploy --template-file outputSamTemplate.yml --stack-name DevDemoStack --capabilities CAPABILITY_IAM --parameter-overrides EnvironmentName=Dev
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml