version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build
  post_build:    
      - sam package --template-file samTemplate.yaml --s3-bucket newpackages --output-template-file outputSamTemplate.yaml
      - sam deploy --template-file outputSamTemplate.yaml --stack-name DevStack --capabilities CAPABILITY_IAM --parameter-overrides EnvironmentName=Dev
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml