version: 0.2
phases:
  build:
    commands:
      - aws sam package --template-file samTemplate.yaml --s3-bucket bk-lambda-pipeline --output-template-file outputSamTemplate.yaml
      - aws sam deploy --template-file outputSamTemplate.yaml --stack-name DevStack1 --capabilities CAPABILITY_IAM --parameter-overrides EnvironmentName=Dev
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml