version: 0.2
phases:
  install:
  build:
    commands:
      - sam package --template-file samTemplate.yaml --s3-bucket newpackages --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml