openapi: "3.0.1"
info:
  title: "DemoAPI"
  description: "Created by OpenAPi Spec"
  version: "2022-01-25T04:32:09Z"
servers:
- url: "https://6u872zvcl9.execute-api.ap-southeast-2.amazonaws.com"
paths:
  /api/posts:
    x-amazon-apigateway-any-method:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/${TestFunction.Arn}/invocations"
        responses:
          ".*":
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /api/show:
    x-amazon-apigateway-any-method:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/${TestFunction1.Arn}/invocations"
        responses:
          ".*":
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"      
components: {}
