openapi: "3.0.1"
info:
  title: "TestFunction-API"
  description: "Created by AWS Lambda"
  version: "2022-01-25T04:32:09Z"
servers:
- url: "https://ha17xui121.execute-api.ap-southeast-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/default"
paths:
  /TestFunction:
    x-amazon-apigateway-any-method:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:275832611856:function:TestFunction/invocations"
        responses:
          ".*":
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
components: {}
