AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM using OpenApi Spec

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: python3.6
    Timeout: 180

Parameters:
  EnvironmentName:
    Description: Select Environment to create resource !
    Default: Dev
    Type: String
    AllowedValues: [prod, Dev , Test]
    ConstraintDescription: must specify prod, Dev.

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref EnvironmentName     
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: openapi.yaml          
            
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TestFunction.lambda_handler
      CodeUri: ./LambdaCode          
      Events:
        ApiGatewayApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/posts
            Method: any

  TestFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TestFunction.lambda_handler
      CodeUri: ./LambdaCode          
      Events:
        ApiGatewayApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/show
            Method: any                